cd "C:\Documents and Settings\Sean Sullivan\My Documents\winBlit"
copy ".\AtLLogApp\src\AtLLogApp.tlb" ".\WinBlitWebBand\Import\Build"
copy ".\AtLLogApp\src\AtLLogApp.tlb" ".\WinBlitPad\Import\Build"
copy ".\AtLLogApp\src\AtLLogApp.tlb" ".\WinBlitExchangeExtension\Import\Build"
copy ".\AtLLogApp\src\AtLLogApp.tlb" ".\WinBlitReaderManager\Import\Build"
copy ".\AtLLogApp\src\AtLLogApp.tlb" ".\WinBlitUtils\Import\Build"
copy ".\AtLLogApp\src\AtLLogApp.tlb" ".\LogStart\Import\Build"
