cd "C:\Documents and Settings\Sean Sullivan\My Documents\winBlit"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager.h" ".\WinBlitWebBand\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager_i.c" ".\WinBlitWebBand\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager_p.c" ".\WinBlitWebBand\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager.h" ".\WinBlitPad\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager_i.c" ".\WinBlitPad\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager_p.c" ".\WinBlitPad\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager.h" ".\WinBlitExchangeExtension\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager_i.c" ".\WinBlitExchangeExtension\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitReaderManager_p.c" ".\WinBlitExchangeExtension\Import\Build"
copy ".\WinBlitReaderManager\src\WinBlitConstants.h" ".\WinBlitPad\src"