//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WinBlitReaderManager.rc
//
#define IDS_PROJNAME                    100
#define IDB_WINBLITREADER               101
#define IDR_WINBLITREADER               102
#define IDR_SETTING                     103
#define IDR_SETTINGS                    104
#define IDR_STATISTIC                   105
#define IDS_SETTING1                    105
#define IDR_STATISTICS                  106
#define IDD_PROPPAGE_SETTINGS           106
#define IDR_BROWSERWRAPPER              107
#define IDS_TRACKBARWINDOW_DESC         108
#define IDR_TrackBarWindow              109
#define IDC_COMBO                       201
#define IDR_CONTEXTMENU                 202
#define IDR_TOOLBAR                     203
#define IDR_WINBLITDATA                 211
#define IDD_CONFIGDIALOG                213
#define IDD_PROPPAGE_DISPLAY            214
#define IDD_PROPPAGE_RULES              215
#define IDD_PROPPAGE_SPEED              216
#define IDD_ADDSETTING_DIALOG           220
#define IDD_ADDRULE_DIALOG              221
#define IDD_REGDIALOG                   222
#define IDR_CONFIGMENU                  226
#define IDD_SPEED_DIALOG                227
#define IDD_DIALOG1                     228
#define IDD_PROPPAGE_FIXATIONS          231
#define IDB_PREVIEW_START               235
#define IDB_PREVIEW_STOP                237
#define IDD_ABOUT_DIALOG                238
#define IDD_SOUND                       239
#define IDD_PROPAGE_SOUND               239
#define IDD_PROPPAGE_SOUND              239
#define IDD_GENERAL                     240
#define IDD_PROPPAGE_GENERAL            240
#define IDC_COMBO_CURRENTSETTING        243
#define IDC_REMOVECONFIGURATIONBUTTON   244
#define IDC_EDIT_REGNAME                245
#define IDC_HIGHLIGHTEDIT               246
#define IDC_ADDCONFIGURATIONBUTTON      247
#define IDC_FIXATIONHEIGHTEDIT          249
#define IDC_FIXATIONWIDTHEDIT           250
#define IDC_CONFIGURATIONNAME_EDIT      252
#define IDC_CONFIGNAME_EDIT             252
#define IDC_CONFIGURATIONTYPE_COMBO     253
#define IDC_TEMPLATE_COMBO              253
#define IDC_ADDBREAKPOINTBUTTON         255
#define IDC_REMOVEBREAKPOINTBUTTON      256
#define IDC_BREAKPOINTS_LIST            257
#define IDC_TEXT_EDIT                   259
#define IDC_PERIOD_EDIT                 260
#define IDC_PAUSE_RADIO                 261
#define IDC_DELAY_RADIO                 262
#define IDC_NAME_EDIT                   263
#define IDC_BACKCOLOR                   264
#define IDC_SCREENFILLCOLOR             265
#define IDC_FIXATIONFILLCOLOR           266
#define IDC_FONT                        267
#define IDC_SCREENTEXTCOLOR             268
#define IDC_FIXATIONTEXTCOLOR           269
#define IDC_CYCLETIMEEDIT               275
#define IDC_SPEED_EDIT                  275
#define IDC_CYCLETIMESLIDER             276
#define IDC_SPEED_SLIDER                276
#define IDC_PERCENTSLIDER               283
#define IDC_FIXTIME_SLIDER              283
#define IDC_DISPLAYSTATIC               284
#define IDC_LEAVEHIGHLIGHTEDCHECK       287
#define IDC_TEMPLATETYPE                288
#define IDC_SOUNDCLICKCHECK             288
#define IDC_STATIC_CURSORWIDTH          289
#define IDC_FIXWIDTHTYPE_STATIC         289
#define IDC_DISPLAYBOXSTATIC            290
#define IDC_LEAVEHIGHLIGHTEDSTATIC      293
#define IDC_EDIT_REGID                  294
#define IDC_SOUNDCLICKSTATIC            294
#define IDC_STATIC_NAME                 295
#define IDC_SHOWTRACKBARSTATIC          295
#define IDC_STATIC_REGID                296
#define IDC_SHOWSTATUSBARSTATIC         296
#define IDC_STATIC_REGTEXT              297
#define IDC_SHOWMETAFILESTATIC          297
#define IDC_IESTATIC                    298
#define IDC_STATIC_COFFTYPE             299
#define IDC_SHOWSTATUSBARSTATIC2        299
#define IDC_STATIC_COFFTIME             300
#define IDC_SHOWMETAFILESTATIC2         300
#define IDC_STATIC_HIGHLIGHTTIME        301
#define IDC_STATIC_COFFVALUE            302
#define IDC_STATICROW                   303
#define IDC_FIXTIMESTATIC               304
#define IDC_CONFIGDESCRIPTION_EDIT      321
#define IDC_FIXWIDTHTYPE_COMBO          323
#define IDC_TEMPLATEDESCRIPTION_STATIC  324
#define IDC_FIXWIDTHDESCRIPTION_STATIC  325
#define IDC_STATIC_WINBLIT              328
#define IDC_PREVIEWSTART_BUTTON         331
#define IDC_PREVIEWSTOP_BUTTON          332
#define IDC_CUSTOM1                     333
#define IDC_STATIC_ABOUTTEXT            335
#define IDC_IPADDRESS2                  336
#define IDC_ABOUT_FILEDESCRIPTION       337
#define IDC_ABOUT_PRODUCTVERSION        338
#define IDC_ABOUT_LEGALCOPYRIGHT        339
#define IDC_ABOUT_COMMENTS              340
#define IDC_ABOUT_VERSION               341
#define IDC_ABOUT_COMPANYNAME           342
#define IDS_WBNAVOGATEFAILED            343
#define IDS_ATLADVISEFAILED             344
#define IDS_QIFORINPLACEFAILED          345
#define IDS_INPLACEACTIVATEFAILED       346
#define IDS_SETSITEFAILED               347
#define IDS_COCREATEWBFAILED            348
#define IDC_MODBREAKPOINTBUTTON         360
#define IDC_COMBO1                      362
#define IDC_COMBO_SOUND                 362
#define IDC_SHOWTOOLBARSTATIC           363
#define IDC_BLITPADSTATIC               366
#define IDC_CLEARSTATISTICS             367

#define IDC_AUTOSTART_IECHECK           368
#define IDC_AUTOSTART_BLITPADCHECK      369
#define IDC_AUTOSTART_WORDCHECK         370
#define IDC_AUTOSTART_OUTLOOKCHECK      371

#define IDC_SHOWSTATUSBARCHECK          372
#define IDC_SHOWMETAFILECHECK           373
#define IDC_SHOWTRACKBARCHECK           374
#define IDC_SHOWTOOLBARCHECK            375

#define ID_CONFIG_ID_START              30000
#define ID_CONFIG_ID_END                30200
#define ID_WORDSPERMINUTE               30501
#define ID_TOTALWORDS                   30502
#define ID_READTIME                     30503
#define IDS_MBXREG                      30504
#define IDS_MBXERROR                    30505
#define IDS_MBXNEWFULL                  30506
#define ID_STARTBUTTON                  31001
#define ID_PAUSEBUTTON                  31002
#define ID_STOPBUTTON                   31003
#define ID_SETTINGS                     31004
#define ID_SHOWTRACKBAR                 31005
#define ID_SHOWCONTROLS                 31006
#define ID_SHOWMETAFILE                 31008
#define ID_SHOWSTATUSBAR                31009
#define ID_CLEARSTATISTICS              31010
#define ID_HELPCALLED                   31011
#define ID_REGISTER                     31012
#define ID_TOP                          31013
#define ID_BOTTOM                       31014
#define ID_SWITCHCONFIG                 31015
#define ID_SPEED                        31016
#define ID_PAGEUP                       31017
#define ID_LINEDOWN                     31018
#define ID_LINEUP                       31019
#define ID_PAGEDOWN                     31020
#define ID_ABOUT_BOX                    31022
#define ID_STARTSTOPTOGGLE              31025
#define ID_FASTER                       31026
#define ID_SLOWER                       31027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        241
#define _APS_NEXT_COMMAND_VALUE         31028
#define _APS_NEXT_CONTROL_VALUE         376
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
